### ISSUE TITLE
M6Tx and tool.tbl not check if tool exist in the table

### ISSUE THREAD

**Issue by alkabal** [machinekit/Cetus#18]
Hi

I work for finish my toolchanger and for this i have try many thing with Axis and Cetus.

In my table i have only 6 tools if i try to set M6T7

Axis display popup tool not in the table and wait for next attempt

Cetus try to execute the command without checking if tool exist and a moment later config is freezed.

if you need more info you can ask.

Best regards

**Comment by alkabal** [comment]
error message is displayed over terminal

/usr/lib/python2.7/dist-packages/pyftpdlib/authorizers.py:240: RuntimeWarning: write permissions assigned to anonymous user.
  RuntimeWarning)
emc/task/emctask.cc 399: interp_error: L'outil demandé 7 n'est pas dans la table d'outils
L'outil demandé 7 n'est pas dans la table d'outils
Exception in thread process_sockets:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/mkwrapper", line 613, in process_sockets
    self.update_error(error)
  File "/usr/bin/mkwrapper", line 1513, in update_error
    text = text.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

**Comment by alkabal** [comment]
Hi again

When opening .ngc file that have a biggest Toolnumber than existing toolnumber in tool.tbl Axis open popup for says M6T7 not in the table, Cetus do not check this.

Br

**Comment by alkabal** [comment]
Hi

The problem is only with french config "sudo dpkg-reconfigure locales"

with english language no problem but with french the ascii é make Cetus crash and message not displayed.

Br
